name: lawazia_pulse
description: "Lawazia Pulse Notification App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  onesignal_flutter: ^5.0.4
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/lawazia.png
    - assets/logo/lawaziawhite.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/lawazia.png"

flutter_native_splash:
  color: "#000000"
  image: assets/logo/lawaziawhite.png
  android: true
  ios: true